2024-11-19 20:43:07,590 - INFO - url: https://aktv.top/live.m3u 获取成功，判断为m3u格式
2024-11-19 20:43:07,824 - ERROR - General error for 美亞電影台(HK): [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,825 - ERROR - General error for ROCK Action: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,827 - ERROR - General error for 鳳凰中文: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,830 - ERROR - General error for Hoy 78: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,839 - ERROR - General error for 明珠剧集台(北美): [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,840 - ERROR - General error for TVBS-新聞台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,841 - ERROR - General error for 中天新聞台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,846 - ERROR - General error for PopC: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,846 - ERROR - General error for 翡翠综合台(北美): [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,853 - ERROR - General error for 黃金翡翠台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,856 - ERROR - General error for 娛樂新聞台(HK): [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,860 - ERROR - General error for Channel 8 HD: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,865 - ERROR - General error for 寰宇新聞台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,866 - ERROR - General error for Channel 5 HD: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,878 - ERROR - General error for myTV SUPER 18台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,878 - ERROR - General error for 翡翠剧集台(北美): [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,880 - ERROR - General error for 千禧經典台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,887 - ERROR - General error for 中天亞洲台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,890 - ERROR - General error for 翡翠台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,895 - ERROR - General error for Channel U HD: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,895 - ERROR - General error for TVBS: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,896 - ERROR - General error for 鳳凰香港: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,896 - ERROR - General error for 靖天電影台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,896 - ERROR - General error for 中視: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,898 - ERROR - General error for 日本全天新聞: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,901 - ERROR - General error for 明珠台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,903 - ERROR - General error for 鳳凰資訊: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,909 - ERROR - General error for 無線新聞台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,909 - ERROR - General error for TVB Plus: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,912 - ERROR - General error for 28 AI 智慧賽馬: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,914 - ERROR - General error for tvN: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,918 - ERROR - General error for 華視: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,992 - ERROR - General error for 美亞電影台(HK): [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,997 - ERROR - General error for 鳳凰中文: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:07,999 - ERROR - General error for ROCK Action: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,015 - ERROR - General error for TVBS-新聞台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,018 - ERROR - General error for 明珠剧集台(北美): [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,033 - ERROR - General error for Hoy 78: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,225 - ERROR - General error for 28 AI 智慧賽馬: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,229 - ERROR - General error for 千禧經典台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,234 - ERROR - General error for Now星影台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,236 - ERROR - General error for 中天新聞台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,248 - ERROR - General error for 明珠台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,248 - ERROR - General error for TVB 星河台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,251 - ERROR - General error for 黃金翡翠台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,251 - ERROR - General error for Channel 8 HD: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,264 - ERROR - General error for viutv 99: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,270 - ERROR - General error for 寰宇新聞台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,270 - ERROR - General error for Channel 5 HD: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,270 - ERROR - General error for 龍華電影台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,275 - ERROR - General error for 鳳凰香港: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,276 - ERROR - General error for 翡翠台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,278 - ERROR - General error for 中視: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,280 - ERROR - General error for 靖天電影台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,280 - ERROR - General error for 龍華經典台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,286 - ERROR - General error for Channel U HD: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,287 - ERROR - General error for PopC: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,289 - ERROR - General error for 翡翠综合台(北美): [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,296 - ERROR - General error for tvN: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,301 - ERROR - General error for TVB Plus: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,305 - ERROR - General error for 龍華日韓台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,306 - ERROR - General error for 鳳凰資訊: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,306 - ERROR - General error for 中天亞洲台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,306 - ERROR - General error for myTV SUPER 18台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,313 - ERROR - General error for 華視: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,313 - ERROR - General error for TVBS: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,314 - ERROR - General error for 日本全天新聞: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,318 - ERROR - General error for 翡翠剧集台(北美): [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,318 - ERROR - General error for 無線新聞台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,352 - ERROR - General error for 娛樂新聞台(HK): [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,366 - ERROR - General error for viutv6 96: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:08,395 - ERROR - General error for 无线新闻台(北美): [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,403 - ERROR - General error for Nick Jr: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,408 - ERROR - General error for NHK World-Japan: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,408 - ERROR - General error for viutv 99: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,413 - ERROR - General error for 無線衛星新聞台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,421 - ERROR - General error for 龍華電影台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,424 - ERROR - General error for ROCK Action: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,433 - ERROR - General error for TVB 星河台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,441 - ERROR - General error for Love Nature HD: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,444 - ERROR - General error for 亞洲新聞台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,452 - ERROR - General error for 東方衛視國際頻道: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,452 - ERROR - General error for 龍華經典台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,454 - ERROR - General error for Animax-HK: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,464 - ERROR - General error for 龍華日韓台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,464 - ERROR - General error for C+台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,465 - ERROR - General error for viutv6 96: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,465 - ERROR - General error for Thrill: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,465 - ERROR - General error for 无线新闻台(北美): [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,465 - ERROR - General error for KIX: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,470 - ERROR - General error for Now星影台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,476 - ERROR - General error for DW: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,477 - ERROR - General error for 爆谷台: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,484 - ERROR - General error for ZooMoo: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,484 - ERROR - General error for France 24: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,484 - ERROR - General error for Nickelodeon: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,528 - ERROR - General error for Nick Jr: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,642 - ERROR - General error for KIX: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,677 - ERROR - General error for DW: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,681 - ERROR - General error for Love Nature HD: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,681 - ERROR - General error for Nickelodeon: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,709 - ERROR - General error for Animax-HK: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
Traceback (most recent call last):
  File "/home/runner/work/iptv/iptv/ffmpeg_util.py", line 29, in check_stream
    result = subprocess.run(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=ffmpeg_timeout)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yunlong.li\\Downloads\\ffmpeg-master-latest-win64-gpl-shared\\bin\\ffmpeg.exe'
2024-11-19 20:43:09,711 - INFO - url: https://aktv.top/live.m3u 读取成功✅，包含频道分类: AKTV
2024-11-19 20:43:09,712 - INFO - Checking channels: 100%|[32m██████████████████████████████████████████████[0m| 1/1 [00:02<00:00,  2.97s/it][0m
2024-11-19 20:43:09,712 - INFO - Checking channels: 100%|[32m██████████████████████████████████████████████[0m| 1/1 [00:02<00:00,  2.97s/it][0m
